---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: redis
  namespace: fleet-default
spec:
  repo: https://https://github.com/vincebrannon/fleet.git
  branch: main
  paths:
    - redis
  clientSecretName: basic-auth-secret
  targets:
    - name: rke-custom
      clusterName: c-5rprr
