---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: rancher-local-storage
  namespace: fleet-default
spec:
  repo: https://https://github.com/vincebrannon/fleet.git
  branch: main
  paths:
    - local-storage
  clientSecretName: basic-auth-secret
  targets:
    - name: all
      clusterSelector: {}
